### ISSUE TITLE
SendAudio

### ISSUE THREAD

**Issue by Cleonia21** [mymmrac/telego#100]
Hi! I can't send the audio correctly. I use this code:

```
func main() {
	botToken := "token"

	bot, err := telego.NewBot(botToken, telego.WithDefaultDebugLogger())
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	updates, _ := bot.UpdatesViaLongPolling(nil)

	defer bot.StopLongPolling()

        //my package for getting audio parameters
	var m music.Music
	m.Authorization()

	for update := range updates {
		if update.Message != nil {
			chatID := tu.ID(update.Message.Chat.ID)

			//getting audio parameters
			params, err := m.GetAudioParams(update.Message.Text)
			if err != nil {
				_, _ = bot.SendMessage(&telego.SendMessageParams{
					ChatID: chatID,
					Text:   err.Error(),
				})
				continue
			}

			//link to download audio
			audio := tu.Audio(chatID, tu.FileByURL(params.URL))
			//filling performer
			audio.WithPerformer(params.Performer)
			//filling title
			audio.WithTitle(params.Title)

			_, _ = bot.SendAudio(audio)
		}
	}
}
```

I get such a debag response:
```
[Mon Apr 24 17:40:17 MSK 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/sendAudio", with data: {"chat_id":848447660,"audio":"https://s147iva.storage.yandex.net/get-mp3/bda9fda28fe66f5e3d4032b4a10bd888/0005fa16d2d871bc/rmusic/U2FsdGVkX19wkWz_DC4Mg4N6EoV332DXOynFrntt3AvzEYKgmcZd93n6fMrhy5u9Mcb7YcBr14nlkBrKxiEvJ2HXUM3AQ7RRFvxNXFkyYGU/575f1549004e4aa8ecc991e6696224e6af4248ddad339812300119ffbff2b6a8/27023","performer":"Performer","title":"Title"}
[Mon Apr 24 17:40:18 MSK 2023] DEBUG API response sendAudio: Ok: true, Err: [<nil>], Result: {"message_id":90,"from":{"id":6210745530,"is_bot":true,"first_name":"ya_music","username":"cleonia_music_bot"},"chat":{"id":848447660,"first_name":"\u0414\u0430\u043d\u0438\u0438\u043b","username":"Cleonia_21","type":"private"},"date":1682347218,"audio":{"duration":171,"file_name":"27023.mp3","mime_type":"audio/mpeg","file_id":"CQACAgQAAxkDAANaZEaU0qB2MyMvdaurhgOqYkDQdaoAAtsDAAIXTDVSLA0Gj1gWr_gvBA","file_unique_id":"AgAD2wMAAhdMNVI","file_size":4116480}}
```

Audio is sent to the user, but title and performer are not added. The sent audio looks like this:
<img width="307" alt="Screenshot 2023-04-24 at 18 01 09" src="https://user-images.githubusercontent.com/84292914/234036529-6e1aa9df-719c-4185-af65-145be251489e.png">

How do I fill in the name of the audio and artist?

**Comment by mymmrac** [comment]
I investigated a bit and seems that this is an issue on the Telegram side. 

Basically, if you are sending audio files that already contain info about the title and performer (for example this file https://file-examples.com/storage/fe0e4ffeec64469f8a2ba23/2017/11/file_example_MP3_700KB.mp3), values specified in fields `Title` and `Performer` will be ignored (and other like `Thumbnail` too).

Also, if you already sent a file, sending the same file (doesn't matter as a file or as file ID or file URL), values will be retrieved from the original (first sent) file.

So, I can't do anything about this, it's just how Telegram and its caching algorithms seem to work, I guess you can ask about this at https://t.me/BotTalk or open a bug here https://bugs.telegram.org.

**Comment by mymmrac** [comment]
> Just in case, I tried sending files that previously didn't exist in Telegram and didn't have title and performer set in metadata, and values were correctly used from those which I specified in the request. So it's most certainly non an issue with Telego

**Comment by Cleonia21** [comment]
I asked this smart person a question (https://github.com/MarshalX ), he knows exactly the right answer. That's what he said to me: "Hi. This is not a bug. Such a priority and restriction when downloading by means of the tg server (by the link to the file). Re-upload the audio file yourself. And it's better to change the tags to the right ones"
