### ISSUE TITLE
KeyboardButtonRequestUser type error

### ISSUE THREAD

**Issue by J3n5en** [mymmrac/telego#122]
### 💬 Telego version

v0.25.1

### 👾 Issue description

https://github.com/mymmrac/telego/blob/ee83ced8e3949842352f7a9a87a5970ad8a0186a/types.go#L1275

when set `UserIsBot = false`  not working.
need to remove the `omitempty`

### ⚡️ Expected behavior

when set `UserIsBot = false`. the request body should have `{"UserIsBot":false}`

**Comment by mymmrac** [comment]
Fixed in [v0.26.0](https://github.com/mymmrac/telego/releases/tag/v0.26.0), please take a look

**Comment by mymmrac** [comment]
Btw, @J3n5en really thanks for reporting the bug )
