### ISSUE TITLE
example is broken Webhook is undefined 

### ISSUE THREAD

**Issue by chromafunk** [mymmrac/telego#123]
### 💬 Telego version

latest

### 👾 Issue description

runing example

undefined: Webhookcompiler[UndeclaredName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredName)

### ⚡️ Expected behavior

it should work

### 🧐 Code example

```Go
https://github.com/mymmrac/telego/blob/main/webhook.go
```

**Comment by mymmrac** [comment]
@chromafunk what example exactly is broken? For me, all of them are compiling without any issues

**Comment by mymmrac** [comment]
@chromafunk please, give more details

**Comment by chromafunk** [comment]
hi, believe this is because you need to get the latest package for the examples to work, which is an step you describe but it's not automatic. After upgrading it worked perfectly. Thanks
