### ISSUE TITLE
List of members in a group

### ISSUE THREAD

**Issue by kehiy** [mymmrac/telego#136]
### ⭐️ Feature description

Add a function which returns list of members in a group

**Comment by mymmrac** [comment]
There is no such functionality in Telegram Bot API itself, the only things you can use are `getChatMemberCount` (count of members) and `getChatMember` (member by it's ID). You can't get member list using Telegram Bot API, you can try to use Telegram client API (Telego can't help you with that, at least right now)

**Comment by kehiy** [comment]
@mymmrac can we add this in the new update? I can help with this

**Comment by mymmrac** [comment]
It's whole new library basically, Telegram client API uses real user account to access the data, all types and methods are completely different, I don't plan to add this into Telego

**Comment by mymmrac** [comment]
Please take a look at https://github.com/gotd/td (or any other similar library)
