### ISSUE TITLE
Cannot send quizzes with `CorrectOptionID = 0`

### ISSUE THREAD

**Issue by Fantailed** [mymmrac/telego#141]
### 💬 Telego version

v0.27.0

### 👾 Issue description

According to the API doc comment, `SendPollParams.CorrectOptionID` is the 0-based index of the correct option in a quiz.

When you create a poll of type quiz where the first answer is correct (i.e. `SendPollParams.CorrectOptionID = 0`), `CorrectOptionID` is not included in the serialized request JSON.  

This leads to the following error when trying to send the poll:
```
telego: sendPoll(): api: 400 "Bad Request: wrong correct option ID specified"
```

This seems to be the case because `SendPollParams.CorrectOptionID` is of type `int`, whose 0-value is 0, and the field has tag `json:"omitempty"`.

### ⚡️ Expected behavior

It should somehow be possible to create poll params with `CorrectOptionID = 0` and include it in the request JSON.

Edit: I see there were similar issues with `omitempty` in the issue history.  
Maybe it would make sense to turn all non-nillable param types into pointers to avoid future issues like this?

### 🧐 Code example

```Go
bot.SendPoll(tu.Poll(tu.ID(chatID, "Question?")).
    WithType(telego.PollTypeQuiz).
    WithOptions("Correct option", "Incorrect option").
    WithCorrectOptionID(0))
```

**Comment by mymmrac** [comment]
Hello, thanks for reporting, fixed in [v0.27.1](https://github.com/mymmrac/telego/releases/tag/v0.27.1)
