### ISSUE TITLE
Cant send remote audio file

### ISSUE THREAD

**Issue by sachinsenal0x64** [mymmrac/telego#163]
### 💬 Telego version
v0.28.0

### 👾 Issue description

API response sendAudio: Ok: false, Err: [400 "Bad Request: failed to get HTTP URL content"]

### ⚡️ Expected behavior
When I use this, everything working fine : https://github.com/cavaliergopher/grab :))

_No response_

### 🧐 Code example

```Go
audioMessage := tu.Audio(
tu.ID(update.Message.Chat.ID),tu.FileFromURL(track[2].URL),).WithReplyToMessageID(update.Message.MessageID
)
bot.SendAudio(audioMessage)
```

**Comment by code-a1** [comment]
For me is working (i tried with a sample mp3 file on the net), is the url you're using correct? Could you share a sample url? Is "track[2].URL" a local file maybe?

**Comment by sachinsenal0x64** [comment]
> For me is working (i tried with a sample mp3 file on the net), is the url you're using correct? Could you share a sample url? Is "track[2].URL" a local file maybe?

URL it corrects :) : https://www.learningcontainer.com/download/sample-flac-file/?wpdmdl=1682&refresh=65ccaa106e7511707911696

![image](https://github.com/mymmrac/telego/assets/127573781/44062f23-89c7-4535-9558-b032f46d1664)

**Comment by sachinsenal0x64** [comment]
> As you can see in the [Telegram API docs](https://core.telegram.org/bots/api#inputfile): _"When sending by URL the target file must have the correct MIME type (e.g., audio/mpeg for [sendAudio](https://core.telegram.org/bots/api#sendaudio), etc.)."_ Trying to send a request with the link you provided the API returns the following error: `Bad Request: wrong file identifier/HTTP URL specified`. A solution could be downloading the file, renaming it and then sending the file url of the file stored in your server to telegram, or just downloading the file and posting it using multipart/form-data (see telegoutil.File() method).

Can I use telegram local bot server with this library ?

**Comment by code-a1** [comment]
If you mean a custom API server, of course, take a look at this: https://pkg.go.dev/github.com/mymmrac/telego#WithAPIServer

**Comment by sachinsenal0x64** [comment]
> If you mean a custom API server, of course, take a look at this: https://pkg.go.dev/github.com/mymmrac/telego#WithAPIServer

Yes, thanks :))

**Comment by sachinsenal0x64** [comment]
I Found the problem telegram only can send 20mb audio remote file :/
