### ISSUE TITLE
How to send a message in markdown v2 formatting containing an inline link?

### ISSUE THREAD

**Issue by rey-bitbee** [mymmrac/telego#175]
### 💬 Telego version

v0.29.2

### 👾 Issue description

How to send a message in markdown v2 formatting containing an inline link like this:
[Link](https://example.com)

### ⚡️ Expected behavior

A text like this:
[Link](https://example.com)

### 🧐 Code example

```Go
text := "\\[Link\\]\\(https://example.com\\)"
msg := tu.Message(tu.ID(query.Message.GetChat().ID), text)
msg.WithParseMode(telego.ModeMarkdownV2)
bot.sendMessage(msg)
```

**Comment by mymmrac** [comment]
You don't need `\\`, just use `"[Link](https://example.com)"`
