### ISSUE TITLE
Typo in telego/pradicates

### ISSUE THREAD

**Issue by AnthonyAspen** [mymmrac/telego#20]
### 💬 Telego version

v0.10.2

### 👾 Issue description

AnyMassage instead of AnyMessage. 

https://github.com/mymmrac/telego/blob/main/telegohandler/pradicates.go#L29

It's a minor typo, not sure worth opening a bug report
later when I feel myself more confident about how this library works, I'll create pull requests directly 

### ⚡️ Expected behavior

AnyMessage

### 🧐 Code example

```Go
// AnyMassage is true if message isn't nil
func AnyMassage() Predicate {
	return func(update telego.Update) bool {
		return update.Message != nil
	}
}
```

**Comment by mymmrac** [comment]
It's okay to create issues, even for small typos, it will help improve the library. And creating PR is also welcomed 🙂, will really appreciate it.
