### ISSUE TITLE
⭐️telego/telegohandler change order of arguments

### ISSUE THREAD

**Issue by AnthonyAspen** [mymmrac/telego#21]
### ⭐️ Feature description

It's kinda odd that "func (h *BotHandler) Handle(handler,`foo`)" takes in handler first, and then path, usually path is the first argument
for example in 
http.Handle("/foo", fooHandler)

### 🌈 Your view

func (h *BotHandler) Handle(predicates ...Predicate,handler Handler)

### 🧐 Code example

```Go
bh.Handle(th.CommandEqual("start"),func(bot *telego.Bot, update telego.Update) {
		// Send message
		_, _ = bot.SendMessage(tu.Message(
			tu.ID(update.Message.Chat.ID),
			fmt.Sprintf("Hello %s!", update.Message.From.FirstName),
		))
	})
```

**Comment by mymmrac** [comment]
Yep, agree, it's unusual to have a handler first, but it's actually done on purpose:

```go
func (h *BotHandler) Handle(handler Handler, predicates ...Predicate)
```

This signature allows you to add any amount of predicates which will be treated as intersection (`AND` operation), for example:

```go
bh.Handle(func(bot *telego.Bot, update telego.Update) { ... }, 
    th.TextContains("one"), th.TextPrefix("two"), th.TextSuffix("three"))
```

This handler will match for a message that contains `one`, has as a prefix `two` and suffix `three`. For example, `two one three` will match.

Making signature look like this:

```go
func (h *BotHandler) Handle(predicates ...Predicate, handler Handler)
```

Isn't allowed by Go, variadic argument should always be the last argument (above code will not compile).
