### ISSUE TITLE
⭐️ telegohandler.HandlerWrapper

### ISSUE THREAD

**Issue by linbuxiao** [mymmrac/telego#36]
### ⭐️ Feature description

It can accept multiple Handlers to return a Handler to simulate a gin-like route capability.

This will provide more power over the original telego handler. Examples include middleware (necessary for authenticated bots), error handling, and more complex logic controls.

If you like the idea, I can submit a PR.

### 🌈 Your view

You can see the code example.

### 🧐 Code example

```Go
package middleware

import (
	"context"
	"github.com/mymmrac/telego"
	"github.com/mymmrac/telego/telegohandler"
	"github.com/mymmrac/telego/telegoutil"
)

type Ctx struct {
	stack        []WrapperHandler
	context      context.Context
	indexHandler int
	update       telego.Update
	bot          *telego.Bot
}

func (c *Ctx) Next() error {
	c.indexHandler++
	if c.indexHandler == len(c.stack) {
		return nil
	}
	h := c.stack[c.indexHandler]
	return h(c)
}

func (c *Ctx) SendMessage(text string) error {
	chatID := telegoutil.ID(c.update.Message.Chat.ID)
	_, err := c.bot.SendMessage(telegoutil.Message(
		chatID,
		text))
	return err
}

type WrapperHandlerBuilder struct {
	ErrorHandler WrapperErrorHandler
	stack        []WrapperHandler
}

func defaultErrorHandler(ctx *Ctx, err error) {
	ctx.SendMessage(err.Error())
}

func (w *WrapperHandlerBuilder) Add(h ...WrapperHandler) {
	w.stack = append(w.stack, h...)
}

func (w *WrapperHandlerBuilder) Build() telegohandler.Handler {
	return func(bot *telego.Bot, update telego.Update) {
		c := &Ctx{
			context:      context.Background(),
			indexHandler: 0,
			update:       update,
			bot:          bot,
		}
		if len(w.stack) == 0 {
			return
		}
		h := w.stack[0]
		if err := h(c); err != nil {
			w.ErrorHandler(c, err)
		}
	}
}

type WrapperHandler func(ctx *Ctx) error
type WrapperErrorHandler func(ctx *Ctx, err error)

func NewWrapperHandlerBuilder() *WrapperHandlerBuilder {
	return &WrapperHandlerBuilder{
		ErrorHandler: defaultErrorHandler,
	}
}

```

**Comment by linbuxiao** [comment]
this change is too bloated, maybe I can start a new repo to support it?

**Comment by mymmrac** [comment]
Hmm, I see what you wanted to achieve, unfortunately for me personally it doesn't fit into current implementation, but still this is great idea and can be either another package of telego (like `telegoctxhandler` or other, I am not great at names :sweat_smile:)  or as you mentioned another repo that will be like a plugin/extension to telego.

In case you think this can be added as package to telego, please fill free to submit a PR, and we will continue with planning and development from that. (I'm personally suggesting this route, but this decision is on you :slightly_smiling_face:)

If you think that this can be its own thing in a separate repo (and I think it can totally be if you wish) I will try to support its development as I can.

**Comment by linbuxiao** [comment]
> Hmm, I see what you wanted to achieve, unfortunately for me personally it doesn't fit into current implementation, but still this is great idea and can be either another package of telego (like `telegoctxhandler` or other, I am not great at names 😅) or as you mentioned another repo that will be like a plugin/extension to telego.
> 
> In case you think this can be added as package to telego, please fill free to submit a PR, and we will continue with planning and development from that. (I'm personally suggesting this route, but this decision is on you 🙂)
> 
> If you think that this can be its own thing in a separate repo (and I think it can totally be if you wish) I will try to support its development as I can.

Thank you for your reply. I will create a new repo to support and try to PR to the main repository when it is close to complete and will restart the issue.
