### ISSUE TITLE
⭐️ Move from Makefile to Taskfile

### ISSUE THREAD

**Issue by mymmrac** [mymmrac/telego#59]
### ⭐️ Feature description

Migrate Makefile to [Taskfile](https://taskfile.dev/)

**Comment by witjem** [comment]
@mymmrac I can do it :)

**Comment by mymmrac** [comment]
@witjem cool, thanks)

I already started, there are some TODOs in file ([Taskfile.yml](https://github.com/mymmrac/telego/blob/main/Taskfile.yml))
