### ISSUE TITLE
⭐️Run 2 and more bots on the same server

### ISSUE THREAD

**Issue by pyxiscloud** [mymmrac/telego#72]
### ⭐️ Feature description

Run 2 bots on the same server with the single golang binary

### 🌈 Your view
Webhook mode
Now we can run only 1 bot. To run 2 and more bot we need polling mode or change ports.
When we try to run second bot - we get error (port busy)
How can we use one fast http server for 2 and more bots?

**Comment by mymmrac** [comment]
Hmm, yep, seems reasonable, I guess there should be a way to do so, but right now it's not possible (because of internal implementation), let me think what can be done and once I will have a plan of solution I will give an update here)

**Comment by pyxiscloud** [comment]
Maybe it will help - for example in tgbotapi works like this:


`	updates := bot.ListenForWebhook("/" + bot.Token) // make channel
	go func() {
		_ = http.ListenAndServe(":8443", nil) // run server to handle requests
	}()`

**Comment by mymmrac** [comment]
Yep, I basically thought about the same thing, but in Telego there is some additional stuff to make sure all updates are processed => it's not that simple to start & stop the server

I think I will create some options to specify your own start & stop functions and it will provide you the ability to start the server differently or something like that

**Comment by mymmrac** [comment]
As a quick and dirty fix for this, I added two new functions (extended already existing functionality). 

Added example of how to set up multiple bots from one server [here](https://github.com/mymmrac/telego/blob/main/examples/multi_bot_webhook/main.go). This should work as of [Telego v0.18.0](https://github.com/mymmrac/telego/releases/tag/v0.18.0).

Please, close this issue if this resolves your problem :slightly_smiling_face: 

For long term solution the API of webhook creation should be changes which will most likely be breaking changes, I briefly described it in #73.

**Comment by mymmrac** [comment]
Hmm, let me try

**Comment by mymmrac** [comment]
There was small typo in my example, I fixed it: a32d17c

Also tried locally, this example works fine

**Comment by pyxiscloud** [comment]
Tried new one, but there are still no incoming messages.
Tried on a server with DNS name...
Same tokens/bots works fine one by one on the same server.

**Comment by mymmrac** [comment]
I tried it locally, and it definitely worked for both bots. I have some ideas why it doesn't work:
- Check that `telego.NewBot` uses different tokens
- Set webhook in Telegram for both bots to respective URLs with `bot1/2.SetWebhook` and `bot1/2.Token()` or any other but different URLs
- Make sure that `bot1/2.UpdatesViaWebhook` gets proper URLs and uses same server & router
- Check order of start/stop sequences

If none of those works, try manually emulate Telegram sending request to your server. This will send empty update to your bot, check for both URLs if it's accessible: 
```shell
curl --url "http://localhost:8080/bot<BOT_TOKEN_1>" -X POST -d "{}"
curl --url "http://localhost:8080/bot<BOT_TOKEN_2>" -X POST -d "{}"
```

On example in repo this definitely works
