### ISSUE TITLE
Typo on LongPolling.

### ISSUE THREAD

**Issue by haashemi** [mymmrac/telego#74]
### 💬 Telego version

v0.18.1

### 👾 Issue description

It's not a _bug_ actually, but it seems like that there is a massive typo on `LongPolling` which is written as `LongPulling`.

I thought that I'm wrong and it's actually LongPulling, but as I checked again and even visited the official docs, it's actually [LongPolling](https://core.telegram.org/bots/api#getupdates)

I wanted to know, was this on purpose or it's a typo or...?

**Comment by mymmrac** [comment]
Hmm, it's actually a typo then 😅 
My first language isn't English, so there might be more such things

I will fix that next time when I will be making breaking changes (hope soon), thanks for reporting 🙂

**Comment by mymmrac** [comment]
Fixed in [v0.19.0](https://github.com/mymmrac/telego/releases/tag/v0.19.0)
