### ISSUE TITLE
👾 Inline Button

### ISSUE THREAD

**Issue by deulizealand** [mymmrac/telego#76]
### 💬 Telego version

0.18.1

### 👾 Issue description

When i want to use inline keyboard button i got response :` API response sendMessage: Ok: false, Err: [400 "Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard"].`

from [this](https://github.com/python-telegram-bot/python-telegram-bot/issues/277#issuecomment-216219774) i found that we should pass more param than only text in tu.InlineKeyboardButton().

when i try to use : 

```
telego.InlineKeyboardButton{
			Text:         "test",
			CallbackData: "yoda",
		},
```

it's work normally.

### ⚡️ Expected behavior

tu.InlineKeyboardButton() can pass optional params for Callback or thing that support in inline Mode

### 🧐 Code example

```
var Inline = tu.InlineKeyboard(
	tu.InlineKeyboardRow(
		tu.InlineKeyboardButton("test"), //  return error like above
		telego.InlineKeyboardButton{ // work
			Text:         "test",
			CallbackData: "yoda",
		},
	),
)
```

**Comment by mymmrac** [comment]
Note: There is no magic behind `tu` package, it only provides some useful functions to make code cleaner, for example:

```go
tu.InlineKeyboardButton("test").WithCallbackData("yoda")
```

It is completely equivalent to this code, just shorter:

```go
telego.InlineKeyboardButton{
    Text:         "test",
    CallbackData: "yoda",
}
```

**Comment by deulizealand** [comment]
I see, Thank you for explanation
