### ISSUE TITLE
API response setWebhook: Ok: false on second call, from UpdatesViaWebhook

### ISSUE THREAD

**Issue by suntong** [mymmrac/telego#99]
I gave the https://github.com/mymmrac/telego/blob/main/examples/updates_webhook/main.go a try, but get `DEBUG API response setWebhook: Ok: false` on second call, from within `UpdatesViaWebhook`:

https://github.com/mymmrac/telego/blob/494c8452a6b485c9fec026241d70f2a844cbe7b3/examples/updates_webhook/main.go#L47-L50

Here is the full log:

```
[Sat Apr 22 23:30:35 EDT 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/setWebhook", with data: {"url":"https://my.server/bot"}
[Sat Apr 22 23:30:35 EDT 2023] DEBUG API response setWebhook: Ok: true, Err: [0 "Webhook is already set"], Result: true
[Sat Apr 22 23:30:35 EDT 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/getWebhookInfo", with data: null
[Sat Apr 22 23:30:35 EDT 2023] DEBUG API response getWebhookInfo: Ok: true, Err: [<nil>], Result: {"url":"https://my.server/bot","has_custom_certificate":false,"pending_update_count":0,"last_error_date":1682219649,"last_error_message":"Connection timed out","max_connections":40,"ip_address":"my.server"}
Webhook Info: &{URL:https://my.server/bot HasCustomCertificate:false PendingUpdateCount:0 IPAddress:my.server LastErrorDate:1682219649 LastErrorMessage:Connection timed out LastSynchronizationErrorDate:0 MaxConnections:40 AllowedUpdates:[]}
[Sat Apr 22 23:30:35 EDT 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/setWebhook", with data: {"url":"https://my.server/bot"}
[Sat Apr 22 23:30:35 EDT 2023] DEBUG API response setWebhook: Ok: false, Err: [429 "Too Many Requests: retry after 1", migrate to chat ID: 0, retry after: 1]
```

Full test code at:
https://github.com/suntong/go_telebot_demos/blob/master/telego/webhook/main.go

**Comment by mymmrac** [comment]
Hi, there is no issue here, maybe the example is a bit misleading.

If you are using `telego.WithWebhookSet` there is no need to call `bot.SetWebhook` separately, the option for webhook is just a helper that will make `bot.SetWebhook` call for you before starting the bot.

Also, you can see error in logs: `Too Many Requests: retry after 1` this means, that you can't call `bot.SetWebhook` two (or more) times too often.

Just remove either `bot.SetWebhook` or `telego.WithWebhookSet` and it will work, I will also add a comment about this in example.

**Comment by mymmrac** [comment]
Updated comments in https://github.com/mymmrac/telego/blob/main/examples/updates_webhook/main.go, so closing this issue

**Comment by mymmrac** [comment]
> if I use either telego.WithWebhookSet or bot.SetWebhook, I get an error: goroutine 1 [running]:
[github.com/mymmrac/telego.FastHTTPWebhookServer.RegisterHandler({{0xface48](http://github.com/mymmrac/telego.FastHTTPWebhookServer.RegisterHandler(%7B%7B0xface48), 0xc000136c78}, 0x0, 0xc00038f5e0, {0xc0001356b0, 0x2e}}, {0xc0000c02c0, 0x33}, 0xc000167cb0)
/root/go/pkg/mod/[github.com/mymmrac/telego@v0.22.1/webhook_server.go:64](http://github.com/mymmrac/telego@v0.22.1/webhook_server.go:64) +0xfc
[github.com/mymmrac/telego.(*Bot).UpdatesViaWebhook(0xc00038f260](http://github.com/mymmrac/telego.(*Bot).UpdatesViaWebhook(0xc00038f260), {0xc0000c02c0, 0x33}, {0xc000151d90, 0x3, 0x3})
/root/go/pkg/mod/[github.com/mymmrac/telego@v0.22.1/webhook.go:88](http://github.com/mymmrac/telego@v0.22.1/webhook.go:88) +0x26a

Otherwise "too many requests"

@suntong can you please update both Telego version (to v0.22.1) and Go version (to 1.19) since it uses generics and if some bugs are present in older version of Telego they still will be fixed only in new one 

I see that in [here](https://github.com/suntong/go_telebot_demos/tree/master/telego) you are using Go 1.17 and Telego 0.20.0

**Comment by suntong** [comment]
Oh, thanks a lot, sure. 
I'm stepping out now, and will do late this afternoon.

**Comment by suntong** [comment]
OK, I gave it a quick test, 

and first of all, there is a typo _"If **t**ou are using this option"_, which is duplicated to two place.

Now, 

I commented out the first one, and build with go 1.19, and here is what I got:

```
[Sun Apr 23 09:22:59 EDT 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/getWebhookInfo", with data: null
[Sun Apr 23 09:23:00 EDT 2023] DEBUG API response getWebhookInfo: Ok: true, Err: [<nil>], Result: {"url":"https://my.server/bot","has_custom_certificate":false,"pending_update_count":1,"last_error_date":1682219649,"last_error_message":"Connection timed out","max_connections":40,"ip_address":"my.server"}
Webhook Info: &{URL:https://my.server/bot HasCustomCertificate:false PendingUpdateCount:1 IPAddress:my.server LastErrorDate:1682219649 LastErrorMessage:Connection timed out LastSynchronizationErrorDate:0 MaxConnections:40 AllowedUpdates:[]}
[Sun Apr 23 09:23:00 EDT 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/setWebhook", with data: {"url":"https://my.server/bot"}
[Sun Apr 23 09:23:00 EDT 2023] DEBUG API response setWebhook: Ok: true, Err: [0 "Webhook is already set"], Result: true
```

I.e., the program exited without getting into the loop of
https://github.com/mymmrac/telego/blob/ff9e4eb154a824087d73dfe5dc813e9cb8e4aa0f/examples/updates_webhook/main.go#L63-L66

I prepared an event, note the `PendingUpdateCount:1` above, but the behavior is the same.

Updating Telego version to v0.22.1 is not helping either, see https://github.com/suntong/go_telebot_demos/commit/1a0aee8708646b92d9476f8a1877f53ac3fcdd15

please double check. thx

**Comment by mymmrac** [comment]
Question, are you running bot with `sudo` (administrator permissions)? Because of if no, then you can't use port `443` (or any port smaller than 1024 as I remember). 

Most likely `bot.StartWebhook("localhost:443")` gives an error like this: 
```
listen tcp4 127.0.0.1:443: bind: permission denied
```

**Comment by mymmrac** [comment]
Also, in example mostly all errors are ignored (for simplicity), but I strongly recommend handling **all** errors

**Comment by suntong** [comment]
Ah, BINGO! -- running as root will not terminate the program right away, just the loop of

`fmt.Printf("Update: %+v\n", update) `

is not reached still, as I don't see any print out, and the `"pending_update_count":1` is still yet. 

Will handling all errors, and do more printing to locate the problem...

**Comment by mymmrac** [comment]
Also, please look at this https://core.telegram.org/bots/webhooks, there are some "rules" to webhooks, for example you can run them only on ports 443, 80, 88, or 8443, and only HTTPS, this should be explicitly specified (for example `https://example.com:8443`) and some other

**Comment by suntong** [comment]
Ah!

in which it says,

> Setting a webhook needs a URL for us to post to. For that you'll need a server with a domain name.

while I'm testing with my home machine using IP address. That must be the reason.
